In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
required_coulumns = ["Pclass" , "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked","Survived","Cabin"]
df = df[required_coulumns].copy()
df

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived Cabin
0         3    male  22.0      1      0   7.2500        S         0   NaN
1         1  female  38.0      1      0  71.2833        C         1   C85
2         3  female  26.0      0      0   7.9250        S         1   NaN
3         1  female  35.0      1      0  53.1000        S         1  C123
4         3    male  35.0      0      0   8.0500        S         0   NaN
..      ...     ...   ...    ...    ...      ...      ...       ...   ...
886       2    male  27.0      0      0  13.0000        S         0   NaN
887       1  female  19.0      0      0  30.0000        S         1   B42
888       3  female   NaN      1      2  23.4500        S         0   NaN
889       1    male  26.0      0      0  30.0000        C         1  C148
890       3    male  32.0      0      0   7.7500        Q         0   NaN

[891 rows x 9 columns]

In [3]:
print("Missing values before preprocessing")
df.isnull().sum()

Missing values before preprocessing

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Survived      0
Cabin       687
dtype: int64

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [5]:
df['Cabin_Known'] = (
    df['Cabin'].notna() &
    (df['Cabin'] != 'unknown')
).astype(int)
df.drop(columns=['Cabin'], inplace=True)

In [7]:
df.tail()

     Pclass     Sex   Age  SibSp  Parch   Fare Embarked  Survived  Cabin_Known
886       2    male  27.0      0      0  13.00        S         0            0
887       1  female  19.0      0      0  30.00        S         1            1
888       3  female  28.0      1      2  23.45        S         0            0
889       1    male  26.0      0      0  30.00        C         1            1
890       3    male  32.0      0      0   7.75        Q         0            0

In [9]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df = pd.get_dummies(df ,columns = ['Embarked'], dtype = int )

In [13]:
scaler = StandardScaler()
df[['Age']] = scaler.fit_transform(df[['Age']])
df[['Fare']] = scaler.fit_transform(df[['Fare']])

In [14]:
df

,Pclass,Sex,Age,SibSp,Parch,Fare,Survived,Cabin_Known,Embarked_C,Embarked_Q,Embarked_S
0,3,1,-0.565736,1,0,-0.502445,0,0,0,0,1
1,1,0,0.663861,1,0,0.786845,1,1,1,0,0
2,3,0,-0.258337,0,0,-0.488854,1,0,0,0,1
3,1,0,0.433312,1,0,0.420730,1,1,0,0,1
4,3,1,0.433312,0,0,-0.486337,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,2,1,-0.181487,0,0,-0.386671,0,0,0,0,1
887,1,0,-0.796286,0,0,-0.044381,1,1,0,0,1
888,3,0,-0.104637,1,2,-0.176263,0,0,0,0,1
889,1,1,-0.258337,0,0,-0.044381,1,1,1,0,0
890,3,1,0.202762,0,0,-0.492378,0,0,0,1,0